
# --- Configurações globais ---
LARGURA, ALTURA = 800, 600
NUM_COMIDAS_INICIAL = 30
NUM_CRIATURAS_INICIAL = 30
PASSOS_GERACAO = 500
FPS = 60
MINIMO_VISAO = 20
MAXIMO_VISAO = 60
MINIMO_VELOCIDADE = 0.1
MAXIMO_VELOCIDADE = 1
VARIACAO_VELOCIDADE = 0.2
VARIACAO_VISAO = 8